### PR TITLE
Kali

### PR DESCRIPTION
**Pull request by sdelafond**
This adds the required autoconf modifications that were missing in #19.

### CODE REVIEW

**Comment by sdelafond** [comment]
@brauner no love for this one? This would really help Kali out :)

**Comment by brauner** [comment]
Thanks. Didn't get notified about this somehow.

**Comment by sdelafond** [comment]
Cheers; I usually hesitate to explicitely ping maintainers, but I just noticed you had merged another PR in February and figured I'd at least get to know if my proposal was subpar or something ;)

**Comment by sdelafond** [comment]
@brauner any chance of an upcoming 3.0.5 release containing those changes?

**Comment by sdelafond** [comment]
Hi @brauner, one last friendly ping to check if a 3.0.5 is somewhat on your radar?

**Comment by brauner** [comment]
@stgraber ?

**Comment by stgraber** [comment]
No timeline on 3.0.5 yet, sorry.

**Pull request merged**
